services:
  db:
    container_name: auth-golang-db
    image: postgres:13
    environment:
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm_password
      POSTGRES_DB: gorm
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  app:
    container_name: auth-golang-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app

volumes:
  postgres_data: