services:
  db:
    image: postgres:13
    container_name: auth-golang-db
    env_file:
      - .env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - backend

  app:
    container_name: auth-golang-app
    build:
      context: .
      dockerfile: Dockerfile
    # image: jorgerr9011/proyectos:auth-golang-app_latest
    # Las líneas "volumes" y "working_dir" solo si no uso imagen (no podía ejecutar migraciones con imagen, mirar!)
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      ENV: ${ENV}
    env_file:
      - .env.production
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
