version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm_password
      POSTGRES_DB: gorm
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USER: gorm
      DB_PASSWORD: gorm_password
      DB_NAME: gorm
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  postgres_data:
